package gov.cms.madie.models.common;

public enum ActionType {
  CREATED,
  VERSIONED_MAJOR,
  VERSIONED_MINOR,
  VERSIONED_REVISIONNUMBER,
  DELETED,
  IMPORTED,
  UPDATED,
  DRAFTED,
  ASSOCIATED,
  SHARED,
  UNSHARED,
  ADJUSTED_BY_ADMIN,
  VERSION_REVERT,
  CREATE_CMSID,
  DELETE_CMSID,
  OWNERSHIP_TRANSFER,
  EXPORTED_MEASURE,
  EXPORTED_TESTCASES,
  ADDED_TO_COMPOSITE,
  REMOVED_FROM_COMPOSITE,
  COMPONENT_ADDED,
  COMPONENT_REMOVED,
  READY_FOR_REVIEW,
  NOT_READY_FOR_REVIEW
}
